name: Build APK with EAS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Authenticate with Expo
        run: eas whoami || eas login --token ${{ secrets.EXPO_TOKEN }}

      - name: Configure EAS
        run: eas build:configure --platform android

      - name: Build APK
        run: eas build -p android --non-interactive --profile preview
